# Generated by Django 4.2.1 on 2023-07-01 19:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appartement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=20)),
                ('Description', models.CharField(max_length=100)),
                ('Address', models.CharField(max_length=40)),
                ('Image1', models.ImageField(upload_to='')),
                ('Image2', models.ImageField(upload_to='')),
                ('Image3', models.ImageField(upload_to='')),
                ('Image4', models.ImageField(upload_to='')),
                ('PrixDay', models.PositiveIntegerField()),
                ('StartDay', models.DateField()),
                ('EndDay', models.DateField()),
                ('NumImmeble', models.PositiveIntegerField()),
                ('NumEtage', models.PositiveIntegerField()),
                ('NumAppartement', models.PositiveIntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MaisonComplet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=20)),
                ('Description', models.CharField(max_length=100)),
                ('Address', models.CharField(max_length=40)),
                ('Image1', models.ImageField(upload_to='')),
                ('Image2', models.ImageField(upload_to='')),
                ('Image3', models.ImageField(upload_to='')),
                ('Image4', models.ImageField(upload_to='')),
                ('PrixDay', models.PositiveIntegerField()),
                ('StartDay', models.DateField()),
                ('EndDay', models.DateField()),
                ('NumMaiCom', models.PositiveIntegerField()),
                ('NombreEtages', models.PositiveIntegerField()),
                ('ToitTerrasse', models.BooleanField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Villa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=20)),
                ('Description', models.CharField(max_length=100)),
                ('Address', models.CharField(max_length=40)),
                ('Image1', models.ImageField(upload_to='')),
                ('Image2', models.ImageField(upload_to='')),
                ('Image3', models.ImageField(upload_to='')),
                ('Image4', models.ImageField(upload_to='')),
                ('PrixDay', models.PositiveIntegerField()),
                ('StartDay', models.DateField()),
                ('EndDay', models.DateField()),
                ('NumVilla', models.PositiveIntegerField()),
                ('Piscine', models.BooleanField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ResrvationVilla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StartDayReser', models.DateField()),
                ('EndDayReser', models.DateField()),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Consulte_poste.villa')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ResrvationMaisonComplet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StartDayReser', models.DateField()),
                ('EndDayReser', models.DateField()),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Consulte_poste.maisoncomplet')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ResrvationAppartement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StartDayReser', models.DateField()),
                ('EndDayReser', models.DateField()),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Consulte_poste.appartement')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
